apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: ghcr.io/the-kube-way/wireguard:latest
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 32M
          limits:
            cpu: 100m
            memory: 32M
        ports:
        - containerPort: LISTEN_PORT
          # hostPort: LISTEN_PORT
          protocol: UDP
        volumeMounts:
        - name: wireguard-conf
          mountPath: /etc/wireguard
        - name: wireguard-port-forwarding
          mountPath: /etc/wireguard-port-forwarding
      volumes:
      - name: wireguard-conf
        secret:
          secretName: wireguard-conf
          defaultMode: 0600
      - name: wireguard-port-forwarding
        configMap:
          name: wireguard-port-forwarding
          items:
          - key: rules.conf
            path: rules.conf

---
apiVersion: v1
kind: Secret
metadata:
  name: wireguard-conf
  labels:
    app: wireguard
stringData:
  wg0.conf: |
    # Put your wireguard config here

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-port-forwarding
  labels:
    app: wireguard
data:
  rules.conf: |
    VPN_INTERFACE CLIENT_IP PROTOCOL SRC_PORT [DEST_PORT]
    e.g., wg0 10.0.0.2 tcp 80 80
