apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: ghcr.io/the-kube-way/wireguard:latest
        securityContext:
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 32M
          limits:
            cpu: 100m
            memory: 32M
        ports:
        - containerPort: LISTEN_PORT
          # hostPort: LISTEN_PORT
          protocol: UDP
        volumeMounts:
        - name: wireguard-conf
          mountPath: /etc/wireguard
      volumes:
      - name: wireguard-conf
        secret:
          secretName: wireguard-conf
          defaultMode: 0600

---
apiVersion: v1
kind: Secret
metadata:
  name: wireguard-conf
  labels:
    app: wireguard
stringData:
  wg0.conf: |
    # Put your wireguard config here
